apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/avilarezende/segportal//k8s/base?ref=09b6d8271945f7ff09276234fd74d95f6941f2c9
  - networkpolicy.yaml

patches:
  - target:
      kind: Ingress
      name: segportal
    patch: |-
      $patch: delete
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: segportal
